name: ai_masters
description: learn AI the smart way.
publish_to: 'none'

# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# https://developer.android.com/studio/publish/versioning
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^3.0.1
  matcher: ^0.12.16+1
  material_color_utilities: ^0.5.0
  web: ^0.1.4-beta

#dev_dependencies:
#  flutter_test:
#    sdk: flutter


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
     - family: Inter
       fonts:
         - asset: fonts/Inter.ttf
